// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WADWebsite.Models;

namespace WADWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WADWebsite.Models.Festival", b =>
                {
                    b.Property<short>("FestivalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("CampingIncluded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FestivalImage")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FestivalName")
                        .IsRequired()
                        .HasColumnType("varchar(23)");

                    b.Property<string>("LineupLink")
                        .HasColumnType("varchar(57)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(22)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TicketPrice")
                        .HasColumnType("decimal(28,0)");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasColumnType("varchar(27)");

                    b.HasKey("FestivalID");

                    b.ToTable("Festivals");
                });
#pragma warning restore 612, 618
        }
    }
}
